### ISSUE TITLE
Flickering with one DM

### ISSUE THREAD

**Issue by Tran-Foxxo** [cheuble/3DiScord#11]
When going to DMs, with only having one scrolling (touch and button) causes the name to flicker and sometimes move to the bottom.  It flickers on the top and bottom.

**Comment by NicoAICP** [comment]
newest version? If yes let me reproduce

**Comment by Tran-Foxxo** [comment]
Yes, I am on the newest version.

**Comment by cheuble** [comment]
If I understand your issue correctly, you only have one DM channel and when you try to scroll, the screen starts flickering, right? If yes, then that is totally normal and isn't really an issue. Why would you want to scroll when you only have one channel...
