### ISSUE TITLE
1.1 and 1.2 crashes on login

### ISSUE THREAD

**Issue by Swampat** [cheuble/3DiScord#12]
When trying to login on either 1.1 or 1.2 the app crashes on when trying to login. 1.0 does not do this when logging in.

**Comment by cheuble** [comment]
Oops, I think I know what that issue is. Can you try this build and tell me if it works?
https://www.dropbox.com/s/o968lgkoqz3f49p/3DiScord.cia?dl=1

**Comment by Swampat** [comment]
new or old build

**Comment by Swampat** [comment]
No it did not work sigh......
