### ISSUE TITLE
Login button doesn't work

### ISSUE THREAD

**Issue by ItsKipz** [cheuble/3DiScord#14]
Can't touch the login button, nothing happens.

**Comment by ItsKipz** [comment]
Seriously, WHY was this released if you can't even log in to the app?

**Comment by Swampat** [comment]
I KNOW RIGHT!

**Comment by cheuble** [comment]
Seriously, WHY was this issue posted if you can't even give information. A log file exists for this specific reason...

**Comment by ItsKipz** [comment]
What info do you need?

In other news, updating to luma 8.0 seemed to fix it, so i guess that was the issue. Dont have the log file from when it didnt work but it works now. Other than that, the app works great, so that's good.

**Comment by CodyMKW** [comment]
login button works fine for me on o3ds with b9s and latest luma

**Comment by GabrielRRussell** [comment]
I can log in. N3DSXL Black, US
