### ISSUE TITLE
When logging in error occurs and code pops up

### ISSUE THREAD

**Issue by Swampat** [cheuble/3DiScord#15]

**Comment by cheuble** [comment]
What version? What is the log? What did you do before? What CFW are you using? What's your FW version? I can't really help if you're just saying me it doesn't work...

**Comment by Swampat** [comment]
Thank and sorry for not being descriptive. The version is 1.2 on the first version I had no problems. The error says there is an exception error I am on 11.4 cfw luma 8.0.
