### ISSUE TITLE
Cannot proceed past login with b9s/luma3ds latest

### ISSUE THREAD

**Issue by MatthewABrantley** [cheuble/3DiScord#17]
Using 3DiScord 1.2, b92 1.2, and Luma 8.1.

Can type my email and password successfully, then when pressing login nothing ever happens.

**Comment by cheuble** [comment]
Hey, is it possible to have your log file? Edit it to remove your email, password and token and paste it there.

**Comment by MatthewABrantley** [comment]
Yeah, it's basically empty :|. 
[log.txt](https://github.com/cheuble/3DiScord/files/1117377/log.txt)


I'll open the application and try a few more times and see if it populates anything else into the log, but I already tried a few times.

**Comment by MatthewABrantley** [comment]
Wow, I had my password wrong. Sorry! Just logged in fine.
