### ISSUE TITLE
Unable to click the login button

### ISSUE THREAD

**Issue by ghost** [cheuble/3DiScord#19]
New 3ds XL 11.4.0 latest release

**Comment by NightScript370** [comment]
Are you logging in from a new place?

If so, you have to check your email.

**Comment by cheuble** [comment]
Hey! Is it possible to have your log file please? It's located at `SD:/3ds/3DiScord/log.txt`. Please edit it to remove your email and token before posting it there though.

**Comment by adrot** [comment]
I can confirm for the same issue, New 3DS XL, 11.5, downloaded from QR.

**Comment by crc-32** [comment]
This shouldn't be closed, I am experiencing the same issue O3DS 11.4

**Comment by NightScript370** [comment]
Its closed because you shouldn't use this. It can get your account banned

**Comment by crc-32** [comment]
How so? It's just a client

**Comment by NightScript370** [comment]
https://gbatemp.net/entry/about-3discord.13037/

**Comment by crc-32** [comment]
Ah, okay. Thanks for clearing that up.
