### ISSUE TITLE
PSA: 3DiScord is dead and can get you banned!

### ISSUE THREAD

**Issue by sks316** [cheuble/3DiScord#22]
Basically, the application doesn't use websockets and spams the API instead. If you want to know more, click the link below.
http://gbatemp.net/entry/about-3discord.13037/

**Comment by cheuble** [comment]
This shouldn't be a real issue...
Besides, it's a duplicate of #9

**Comment by sks316** [comment]
I just thought people should know it's dead and can get you banned since that isn't explicitly stated in #9, so...
