### ISSUE TITLE
Crashes the second I sign in (data abort)

### ISSUE THREAD

**Issue by Aluminite** [cheuble/3DiScord#3]
There's not really that much more to say, but here is my crash dump:
[https://transfer.sh/AMCDl/crash_dump_00000027.dmp](https://transfer.sh/AMCDl/crash_dump_00000027.dmp)
(I've manually removed the email and password from the dump, not that much of an idiot lul)
o3ds xl on 11.4 if that helps

**Comment by cheuble** [comment]
This is weird, never had that crash. Did you try logging in with another account and/or deleting the file `SD:/3ds/3DiScord/3DiScord-userdata.txt`?

**Comment by ghost** [comment]
Even i ista-crash when i log-in i deleted two times the file in SD:/3dss/3DiScord/3DiScord-userdata.txt plus i removed and re-install the cia via qr-code im on n3ds v.11.4 but i know that works on n3ds by the new video of TCPixel but on my 3ds don't work .
(im italian and if i do mistake im sorry and i do not won't offend the owner of this app if i do offend she/he)

**Comment by cheuble** [comment]
Did you try with the new version?

**Comment by ghost** [comment]
Same thing

**Comment by cheuble** [comment]
Is it possible to have your `SD:/3ds/3DiScord/log.txt` file? Did you try logging in with another account?

**Comment by ghost** [comment]
Here is the log: -snip, contains your token-
No, i don't try with an other accont because i've do not have an other account

**Comment by cheuble** [comment]
@xXDavidX That's because you have no DM channel. Start a DM conversation with someone and it *should* fix the issue. This is a bug and needs to be fixed in the next update

**Comment by ghost** [comment]
Oh, thanks i've added an channel time ago but i think that discord has deleted it...
Thanks again.

**Comment by cheuble** [comment]
Did it fix the issue?

**Comment by ghost** [comment]
Yes it fix it
