### ISSUE TITLE
Clicking DMs causes an instant crash.

### ISSUE THREAD

**Issue by ClammyMantis488** [cheuble/3DiScord#6]
Not much more to explain from the title. Here is my crash dump if that helps at all. [crash_dump_00000016.dmp](https://cdn.discordapp.com/attachments/296874845822779393/327285374269390858/crash_dump_00000016.dmp)

**Comment by cheuble** [comment]
Sending the file `SD:/3ds/3DiScord/log.txt` would be preferable.
