### ISSUE TITLE
No official white theme.

### ISSUE THREAD

**Issue by NathanDreamweaver** [cheuble/3DiScord#7]
I think this is an issue. There IS an unofficial white theme, but official is better.

**Comment by cheuble** [comment]
Added custom themes to my TODO list. I plan to add them in the next update

**Comment by KevinX8** [comment]
but you are not adding white theme right? RIGHT?

**Comment by cheuble** [comment]
I'm adding custom themes with every colour and images customizable

**Comment by NicoAICP** [comment]
Then I'll make a theme you didn't make :^) (i will continue making themes)
